//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace format_converter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("format_converter.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string button_cancel_text {
            get {
                return ResourceManager.GetString("button.cancel.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        internal static string button_convert_text {
            get {
                return ResourceManager.GetString("button.convert.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lang files (*.lang).
        /// </summary>
        internal static string filter_lang_desc {
            get {
                return ResourceManager.GetString("filter.lang.desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lang files (*.xliff).
        /// </summary>
        internal static string filter_xliff_desc {
            get {
                return ResourceManager.GetString("filter.xliff.desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file.
        /// </summary>
        internal static string main_file_new {
            get {
                return ResourceManager.GetString("main.file.new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open files.
        /// </summary>
        internal static string main_file_open {
            get {
                return ResourceManager.GetString("main.file.open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input:.
        /// </summary>
        internal static string main_input_label {
            get {
                return ResourceManager.GetString("main.input.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected.
        /// </summary>
        internal static string main_label_nopath {
            get {
                return ResourceManager.GetString("main.label.nopath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert mode.
        /// </summary>
        internal static string main_mode_invert {
            get {
                return ResourceManager.GetString("main.mode.invert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output:.
        /// </summary>
        internal static string main_output_label {
            get {
                return ResourceManager.GetString("main.output.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log output....
        /// </summary>
        internal static string main_text_notext {
            get {
                return ResourceManager.GetString("main.text.notext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string main_toolbar_file {
            get {
                return ResourceManager.GetString("main.toolbar.file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string main_toolbar_lang {
            get {
                return ResourceManager.GetString("main.toolbar.lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current mode: {0}.
        /// </summary>
        internal static string main_toolbar_mode {
            get {
                return ResourceManager.GetString("main.toolbar.mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .lang to .xliff converter.
        /// </summary>
        internal static string main_window_title {
            get {
                return ResourceManager.GetString("main.window.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lang to xliff.
        /// </summary>
        internal static string mode_lang_xliff {
            get {
                return ResourceManager.GetString("mode.lang.xliff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file is NOT a XML file!{0}Please select a valid XML file and try again.
        /// </summary>
        internal static string popup_badxml_desc {
            get {
                return ResourceManager.GetString("popup.badxml.desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion completed.
        /// </summary>
        internal static string popup_convdone_desc {
            get {
                return ResourceManager.GetString("popup.convdone.desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to convert?.
        /// </summary>
        internal static string popup_convstart_desc {
            get {
                return ResourceManager.GetString("popup.convstart.desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to convert.
        /// </summary>
        internal static string popup_convstart_title {
            get {
                return ResourceManager.GetString("popup.convstart.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string popup_error_title {
            get {
                return ResourceManager.GetString("popup.error.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not selected!.
        /// </summary>
        internal static string popup_nofile_desc {
            get {
                return ResourceManager.GetString("popup.nofile.desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected.
        /// </summary>
        internal static string popup_nofile_title {
            get {
                return ResourceManager.GetString("popup.nofile.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files selected. Select now?.
        /// </summary>
        internal static string popup_nofileselect_desc {
            get {
                return ResourceManager.GetString("popup.nofileselect.desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is running. Do you want to cancel it?{0}Note: you will lose all unsaved progress.
        /// </summary>
        internal static string popup_opruns_desc {
            get {
                return ResourceManager.GetString("popup.opruns.desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel operation?.
        /// </summary>
        internal static string popup_opruns_title {
            get {
                return ResourceManager.GetString("popup.opruns.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string popup_warn_title {
            get {
                return ResourceManager.GetString("popup.warn.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string text_cancel {
            get {
                return ResourceManager.GetString("text.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has {1} strings.
        /// </summary>
        internal static string text_desc_lang {
            get {
                return ResourceManager.GetString("text.desc.lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input length: {0}.
        /// </summary>
        internal static string text_desc_length1 {
            get {
                return ResourceManager.GetString("text.desc.length1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output length: {0}.
        /// </summary>
        internal static string text_desc_length2 {
            get {
                return ResourceManager.GetString("text.desc.length2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has {1} strings of whom {2} translated and {3} untranslated.
        /// </summary>
        internal static string text_desc_xliff {
            get {
                return ResourceManager.GetString("text.desc.xliff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} matches found and converted.
        /// </summary>
        internal static string text_done {
            get {
                return ResourceManager.GetString("text.done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file 1....
        /// </summary>
        internal static string text_load1 {
            get {
                return ResourceManager.GetString("text.load1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file 2....
        /// </summary>
        internal static string text_load2 {
            get {
                return ResourceManager.GetString("text.load2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting....
        /// </summary>
        internal static string text_noprogress {
            get {
                return ResourceManager.GetString("text.noprogress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1}.
        /// </summary>
        internal static string text_progress {
            get {
                return ResourceManager.GetString("text.progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string text_ready {
            get {
                return ResourceManager.GetString("text.ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Input....
        /// </summary>
        internal static string text_sel1 {
            get {
                return ResourceManager.GetString("text.sel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open input file....
        /// </summary>
        internal static string text_sel1_title {
            get {
                return ResourceManager.GetString("text.sel1.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Output....
        /// </summary>
        internal static string text_sel2 {
            get {
                return ResourceManager.GetString("text.sel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open output file....
        /// </summary>
        internal static string text_sel2_title {
            get {
                return ResourceManager.GetString("text.sel2.title", resourceCulture);
            }
        }
    }
}
